import { Task } from './types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    taskCode: 'EST-988',
    title: 'Implement new API endpoint for user auth & session token management',
    redmineUrl: 'https://redmine.example.com/issues/988',
    status: 'DOING',
    planDevUp: '2023-10-10',
    actDevUp: '',
    createdAt: '2023-10-01',
    actStart: '2023-10-05',
    actEnd: '',
    releaseDate: '2023-10-25',
    hasBlocker: false,
    blockerDescription: '',
    note: 'Waiting on UI assets from design team before finalizing response contracts.',
    assignee: 'Nguyễn Đình Duy',
    priority: 'High',
    subtasks: [
      {
        id: 'sub-1-1',
        title: 'Design DB Schema & Migrations',
        status: 'DONE',
        createdAt: '2023-10-01',
        assignee: 'Duy ND',
      },
      {
        id: 'sub-1-2',
        title: 'Develop API Logic & Auth Middleware',
        status: 'DOING',
        createdAt: '2023-10-05',
        assignee: 'Duy ND',
      },
      {
        id: 'sub-1-3',
        title: 'Write Unit Tests & Swagger Docs',
        status: 'TODO',
        createdAt: '2023-10-06',
        assignee: 'Minh Tuấn',
      },
    ],
  },
  {
    id: 'task-2',
    taskCode: 'EST-992',
    title: 'Migrate legacy data to new PostgreSQL cluster with zero-downtime replication',
    redmineUrl: 'https://redmine.example.com/issues/992',
    status: 'BLOCKED',
    planDevUp: '2023-10-12',
    actDevUp: '',
    createdAt: '2023-10-02',
    actStart: '2023-10-08',
    actEnd: '',
    releaseDate: '2023-10-25',
    hasBlocker: true,
    blockerDescription: 'DB Server connection timeout issue #443 (Staging firewall blocking port 5432)',
    note: 'Need DevOps support to open port 5432 on staging environment and whitelist gateway IP.',
    assignee: 'Hoàng Long',
    priority: 'Urgent',
    subtasks: [
      {
        id: 'sub-2-1',
        title: 'Data Validation Script & Integrity Check',
        status: 'BLOCKED',
        createdAt: '2023-10-02',
        notes: 'Blocked by firewall port 5432',
        assignee: 'Hoàng Long',
      },
    ],
  },
  {
    id: 'task-3',
    taskCode: 'EST-1004',
    title: 'Update privacy policy links, GDPR compliance cookies banner in footer',
    redmineUrl: 'https://redmine.example.com/issues/1004',
    status: 'DONE',
    planDevUp: '2023-10-08',
    actDevUp: '2023-10-08',
    createdAt: '2023-10-05',
    actStart: '2023-10-07',
    actEnd: '2023-10-08',
    releaseDate: '2023-10-15',
    hasBlocker: false,
    blockerDescription: '',
    note: 'Passed QA verification in staging environment smoothly.',
    assignee: 'Thu Hà',
    priority: 'Low',
    subtasks: [
      {
        id: 'sub-3-1',
        title: 'Update EN copy & translations table',
        status: 'DONE',
        createdAt: '2023-10-05',
        assignee: 'Thu Hà',
      },
      {
        id: 'sub-3-2',
        title: 'Update VN copy & legal validation',
        status: 'DONE',
        createdAt: '2023-10-05',
        assignee: 'Thu Hà',
      },
    ],
  },
  {
    id: 'task-4',
    taskCode: 'EST-1015',
    title: 'Optimize SQL queries for dashboard reports and metrics caching',
    redmineUrl: 'https://redmine.example.com/issues/1015',
    status: 'DOING',
    planDevUp: '2023-10-18',
    actDevUp: '',
    createdAt: '2023-10-08',
    actStart: '2023-10-09',
    actEnd: '',
    releaseDate: '2023-10-30',
    hasBlocker: false,
    blockerDescription: '',
    note: 'Redis caching layer reduced response time from 1.4s to 85ms.',
    assignee: 'Quốc Bảo',
    priority: 'Medium',
    subtasks: [
      {
        id: 'sub-4-1',
        title: 'Add composite index on user_id & created_at',
        status: 'DONE',
        createdAt: '2023-10-08',
        assignee: 'Quốc Bảo',
      },
      {
        id: 'sub-4-2',
        title: 'Implement Redis memory store cache adapter',
        status: 'DOING',
        createdAt: '2023-10-09',
        assignee: 'Quốc Bảo',
      },
    ],
  },
  {
    id: 'task-5',
    taskCode: 'EST-1022',
    title: 'Integrate Webhook notifications for Redmine and Slack integration',
    redmineUrl: 'https://redmine.example.com/issues/1022',
    status: 'TODO',
    planDevUp: '2023-10-22',
    actDevUp: '',
    createdAt: '2023-10-10',
    actStart: '',
    actEnd: '',
    releaseDate: '2023-11-05',
    hasBlocker: false,
    blockerDescription: '',
    note: 'Specification document approved by tech lead.',
    assignee: 'Minh Tuấn',
    priority: 'Medium',
    subtasks: [
      {
        id: 'sub-5-1',
        title: 'Slack Webhook Payload Formatter',
        status: 'TODO',
        createdAt: '2023-10-10',
        assignee: 'Minh Tuấn',
      },
    ],
  },
];
